# Generated by Django 5.0.2 on 2024-02-26 16:29
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("enrollment_start", models.DateField(blank=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "lunes"),
                            ("tuesday", "martes"),
                            ("wednesday", "miércoles"),
                            ("thursday", "jueves"),
                            ("friday", "viernes"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkshopPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_students", models.PositiveIntegerField(default=0)),
                ("cycles", models.ManyToManyField(to="cayuman.cycle")),
                (
                    "period",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cayuman.period"),
                ),
                ("schedules", models.ManyToManyField(to="cayuman.schedule")),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cayuman.workshop",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cayuman.member"),
                ),
            ],
            options={
                "unique_together": {
                    ("workshop", "period"),
                    ("workshop", "period", "teacher"),
                },
            },
        ),
        migrations.CreateModel(
            name="StudentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cayuman.cycle"),
                ),
                (
                    "workshop_periods",
                    models.ManyToManyField(blank=True, to="cayuman.workshopperiod"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cayuman.member"),
                ),
            ],
            options={
                "ordering": ["date_joined"],
                "get_latest_by": "date_joined",
            },
        ),
    ]
