# Generated by Django 5.0.2 on 2024-02-29 16:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycle",
            options={"verbose_name": "Ciclo", "verbose_name_plural": "Ciclos"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Miembro", "verbose_name_plural": "Miembros"},
        ),
        migrations.AlterModelOptions(
            name="period",
            options={"verbose_name": "Periodo", "verbose_name_plural": "Periodos"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "verbose_name": "Bloque Horario",
                "verbose_name_plural": "Bloques Horarios",
            },
        ),
        migrations.AlterModelOptions(
            name="studentcycle",
            options={
                "get_latest_by": "date_joined",
                "ordering": ["date_joined"],
                "verbose_name": "Estudiante en ciclo",
                "verbose_name_plural": "Estudiantes en ciclos",
            },
        ),
        migrations.AlterModelOptions(
            name="workshop",
            options={"verbose_name": "Taller", "verbose_name_plural": "Talleres"},
        ),
        migrations.AlterModelOptions(
            name="workshopperiod",
            options={
                "verbose_name": "Taller por periodo",
                "verbose_name_plural": "Talleres por periodo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="workshopperiod",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Lunes"),
                    ("tuesday", "Martes"),
                    ("wednesday", "Miércoles"),
                    ("thursday", "Jueves"),
                    ("friday", "Viernes"),
                ],
                max_length=10,
            ),
        ),
    ]
