# Generated by Django 5.0.2 on 2024-03-14 14:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0002_alter_cycle_options_alter_member_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="full_name",
            field=models.TextField(blank=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="period",
            name="date_end",
            field=models.DateField(verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="period",
            name="date_start",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="period",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="period",
            name="enrollment_start",
            field=models.DateField(blank=True, verbose_name="Enrollment start date"),
        ),
        migrations.AlterField(
            model_name="period",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                ],
                max_length=10,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time_end",
            field=models.TimeField(verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time_start",
            field=models.TimeField(verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="studentcycle",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cayuman.cycle",
                verbose_name="Cycle",
            ),
        ),
        migrations.AlterField(
            model_name="studentcycle",
            name="date_joined",
            field=models.DateField(auto_now_add=True, verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="studentcycle",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cayuman.member",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="studentcycle",
            name="workshop_periods",
            field=models.ManyToManyField(blank=True, to="cayuman.workshopperiod", verbose_name="Workshop Periods"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="cycles",
            field=models.ManyToManyField(to="cayuman.cycle", verbose_name="Cycles"),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="max_students",
            field=models.PositiveIntegerField(default=0, verbose_name="Max Students"),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cayuman.period",
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="schedules",
            field=models.ManyToManyField(to="cayuman.schedule", verbose_name="Schedules"),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cayuman.member",
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="workshopperiod",
            name="workshop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cayuman.workshop",
                verbose_name="Workshop",
            ),
        ),
    ]
