# Generated by Django 5.0.2 on 2024-04-22 01:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0003_workshop_full_name_alter_cycle_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="enrollment_end",
            field=models.DateField(blank=True, null=True, verbose_name="Enrollment end date"),
        ),
    ]
