# Generated by Django 5.0.2 on 2024-06-16 01:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0005_period_preview_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="enrollment_start",
            field=models.DateTimeField(blank=True, verbose_name="Enrollment start date and time"),
        ),
    ]
