# Generated by Django 5.0.2 on 2024-09-22 23:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0006_alter_period_enrollment_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="enrollment_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Enrollment end date and time"),
        ),
    ]
