# Generated by Django 5.1.6 on 2025-02-28 18:47
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cayuman", "0006_alter_period_enrollment_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "is_selectable",
                    models.BooleanField(
                        default=False,
                        help_text=_("Whether students can choose activities of this type"),
                        verbose_name=_("Is selectable"),
                    ),
                ),
                (
                    "requires_attendance",
                    models.BooleanField(default=True, help_text=_("Whether attendance should be tracked"), verbose_name=_("Requires attendance")),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Activity type-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Activity type"),
                "verbose_name_plural": _("Activity types"),
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name=_("Metadata"))),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Event type"),
                "verbose_name_plural": _("Event types"),
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Subject-specific attributes like curriculum links"),
                        verbose_name=_("Metadata"),
                    ),
                ),
            ],
            options={
                "verbose_name": _("Subject"),
                "verbose_name_plural": _("Subjects"),
            },
        ),
        migrations.CreateModel(
            name="SubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "is_selectable",
                    models.BooleanField(
                        default=False,
                        help_text=_("Whether students can choose subjects of this type"),
                        verbose_name=_("Is selectable"),
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Type-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Subject type"),
                "verbose_name_plural": _("Subject types"),
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                ("date_start", models.DateField(verbose_name=_("Start date"))),
                ("date_end", models.DateField(verbose_name=_("End date"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Attributes specific to this term instance"),
                        verbose_name=_("Metadata"),
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start"],
                "verbose_name": _("Term"),
                "verbose_name_plural": _("Terms"),
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", _("Monday")),
                            ("tuesday", _("Tuesday")),
                            ("wednesday", _("Wednesday")),
                            ("thursday", _("Thursday")),
                            ("friday", _("Friday")),
                            ("saturday", _("Saturday")),
                            ("sunday", _("Sunday")),
                        ],
                        max_length=10,
                        verbose_name=_("Day of week"),
                    ),
                ),
                ("time_start", models.TimeField(verbose_name=_("Time start"))),
                ("time_end", models.TimeField(verbose_name=_("Time end"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Time slot-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Time slot"),
                "verbose_name_plural": _("Time slots"),
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                (
                    "group_type",
                    models.CharField(
                        help_text=_("The type of group (e.g., Grade, Cycle, Team)"),
                        max_length=50,
                        verbose_name=_("Group type"),
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text=_("Whether members must belong to exactly one group of this type"),
                        verbose_name=_("Is primary"),
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Attributes specific to this group instance"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_groups",
                        to="smiles.group",
                        verbose_name=_("Parent"),
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "group_type")},
                "verbose_name": _("Group"),
                "verbose_name_plural": _("Groups"),
            },
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Template-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "applicable_groups",
                    models.ManyToManyField(related_name="schedule_templates", to="smiles.group", verbose_name=_("Applicable groups")),
                ),
                (
                    "applicable_terms",
                    models.ManyToManyField(related_name="schedule_templates", to="smiles.term", verbose_name=_("Applicable terms")),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Schedule template"),
                "verbose_name_plural": _("Schedule templates"),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                (
                    "preview_date",
                    models.DateTimeField(
                        blank=True,
                        help_text=_("When information about this event becomes visible"),
                        null=True,
                        verbose_name=_("Preview date"),
                    ),
                ),
                ("date_start", models.DateTimeField(verbose_name=_("Start date"))),
                ("date_end", models.DateTimeField(verbose_name=_("End date"))),
                ("is_active", models.BooleanField(default=True, verbose_name=_("Is active"))),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name=_("Metadata"))),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="smiles.eventtype",
                        verbose_name=_("Type"),
                    ),
                ),
                (
                    "affects_groups",
                    models.ManyToManyField(blank=True, related_name="events", to="smiles.group", verbose_name=_("Affects groups")),
                ),
                (
                    "affects_subjects",
                    models.ManyToManyField(blank=True, related_name="events", to="smiles.subject", verbose_name=_("Affects subjects")),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text=_("Term this event is associated with"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smiles.term",
                        verbose_name=_("Term"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Event"),
                "verbose_name_plural": _("Events"),
            },
        ),
        migrations.CreateModel(
            name="SubjectOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_students",
                    models.PositiveIntegerField(default=0, help_text=_("0 means unlimited"), verbose_name=_("Max students")),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Offering-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "eligible_groups",
                    models.ManyToManyField(related_name="eligible_offerings", to="smiles.group", verbose_name=_("Eligible groups")),
                ),
                (
                    "enrollment_event",
                    models.ForeignKey(
                        blank=True,
                        help_text=_("Enrollment event associated with this offering"),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_offerings",
                        to="smiles.event",
                        verbose_name=_("Enrollment event"),
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="smiles.subject",
                        verbose_name=_("Subject"),
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_offerings",
                        to="cayuman.member",
                        verbose_name=_("Teacher"),
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_offerings",
                        to="smiles.term",
                        verbose_name=_("Term"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("Subject offering"),
                "verbose_name_plural": _("Subject offerings"),
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                ("description", models.TextField(blank=True, verbose_name=_("Description"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Activity-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="smiles.activitytype",
                        verbose_name=_("Type"),
                    ),
                ),
                (
                    "applicable_groups",
                    models.ManyToManyField(related_name="applicable_activities", to="smiles.group", verbose_name=_("Applicable groups")),
                ),
                (
                    "subject_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="smiles.subjectoffering",
                        verbose_name=_("Subject offering"),
                    ),
                ),
            ],
            options={
                "verbose_name_plural": _("Activities"),
                "verbose_name": _("Activity"),
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="smiles.subjecttype",
                verbose_name=_("Type"),
            ),
        ),
        migrations.CreateModel(
            name="MemberSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_custom", models.BooleanField(default=False, verbose_name=_("Is custom"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Schedule-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="cayuman.member",
                        verbose_name=_("Member"),
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_schedules",
                        to="smiles.scheduletemplate",
                        verbose_name=_("Template"),
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_schedules",
                        to="smiles.term",
                        verbose_name=_("Term"),
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "term")},
                "verbose_name": _("Member schedule"),
                "verbose_name_plural": _("Member schedules"),
            },
        ),
        migrations.CreateModel(
            name="SpecialDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name=_("Name"))),
                ("date", models.DateField(verbose_name=_("Date"))),
                ("is_school_closed", models.BooleanField(default=False, verbose_name=_("Is school closed"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Special day-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "affects_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=_("Empty means all groups are affected"),
                        related_name="special_days",
                        to="smiles.group",
                        verbose_name=_("Affects groups"),
                    ),
                ),
                (
                    "alternate_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="special_days",
                        to="smiles.scheduletemplate",
                        verbose_name=_("Alternate schedule"),
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "date")},
                "verbose_name": _("Special day"),
                "verbose_name_plural": _("Special days"),
            },
        ),
        migrations.CreateModel(
            name="MemberGroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_assigned", models.DateField(auto_now_add=True, verbose_name=_("Date assigned"))),
                ("is_active", models.BooleanField(default=True, verbose_name=_("Is active"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Assignment-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_assignments",
                        to="smiles.group",
                        verbose_name=_("Group"),
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="cayuman.member",
                        verbose_name=_("Member"),
                    ),
                ),
                (
                    "subject_offerings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_members",
                        to="smiles.subjectoffering",
                        verbose_name=_("Subject offerings"),
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "group", "is_active")},
                "verbose_name": _("Member group assignment"),
                "verbose_name_plural": _("Member group assignments"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("name", "type")},
        ),
        migrations.CreateModel(
            name="ScheduleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Assignment-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_assignments",
                        to="smiles.activity",
                        verbose_name=_("Activity"),
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="smiles.scheduletemplate",
                        verbose_name=_("Template"),
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_assignments",
                        to="smiles.timeslot",
                        verbose_name=_("Time slot"),
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "time_slot")},
                "verbose_name": _("Schedule assignment"),
                "verbose_name_plural": _("Schedule assignments"),
            },
        ),
        migrations.CreateModel(
            name="MemberScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text=_("Specific date (blank means recurring every week)"),
                        null=True,
                        verbose_name=_("Date"),
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name=_("Reason"))),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Override-specific attributes"),
                        verbose_name=_("Metadata"),
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="smiles.activity",
                        verbose_name=_("Activity"),
                    ),
                ),
                (
                    "member_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="smiles.memberschedule",
                        verbose_name=_("Member schedule"),
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_overrides",
                        to="smiles.timeslot",
                        verbose_name=_("Time slot"),
                    ),
                ),
            ],
            options={
                "unique_together": {("member_schedule", "date", "time_slot")},
                "verbose_name": _("Member schedule override"),
                "verbose_name_plural": _("Member schedule overrides"),
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("attended", models.BooleanField(default=True)),
                ("early_dismissal_time", models.TimeField(blank=True, null=True)),
                ("late_arrival_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Attendance-specific attributes",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="smiles.activity",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="cayuman.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendance",
                        to="cayuman.member",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="smiles.timeslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "date", "time_slot")},
            },
        ),
    ]
