# Generated by Django 5.1.6 on 2025-02-28 18:47
from django.db import migrations


def create_subject_types(apps, schema_editor):
    """
    Create default subject types needed for the system.
    """
    SubjectType = apps.get_model("smiles", "SubjectType")

    # Create Workshop subject type
    SubjectType.objects.get_or_create(name="Workshop", defaults={"description": "Workshop activities", "is_selectable": True})

    # Create other common subject types
    subject_types = [
        {"name": "Academic", "description": "Academic subjects", "is_selectable": False},
        {"name": "Extracurricular", "description": "Extracurricular activities", "is_selectable": True},
    ]

    for st_data in subject_types:
        SubjectType.objects.get_or_create(
            name=st_data["name"], defaults={"description": st_data["description"], "is_selectable": st_data["is_selectable"]}
        )


def reverse_subject_types(apps, schema_editor):
    """
    Remove created subject types.
    """
    SubjectType = apps.get_model("smiles", "SubjectType")
    SubjectType.objects.filter(name__in=["Workshop", "Academic", "Extracurricular"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_subject_types, reverse_subject_types),
    ]
