# Generated by Django 5.1.6 on 2025-02-28 18:47
from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_subject_types(apps, schema_editor):
    """
    Create default subject types needed for the system.
    """
    SubjectType = apps.get_model("smiles", "SubjectType")

    # Create Workshop subject type
    SubjectType.objects.get_or_create(name=_("Workshop"), defaults={"description": _("Workshop activities"), "is_selectable": True})

    # Create other common subject types
    subject_types = [
        {"name": _("Academic"), "description": _("Academic subjects"), "is_selectable": False},
        {"name": _("Extracurricular"), "description": _("Extracurricular activities"), "is_selectable": True},
    ]

    for st_data in subject_types:
        SubjectType.objects.get_or_create(
            name=st_data["name"], defaults={"description": st_data["description"], "is_selectable": st_data["is_selectable"]}
        )


def reverse_subject_types(apps, schema_editor):
    """
    Remove created subject types.
    """
    SubjectType = apps.get_model("smiles", "SubjectType")
    SubjectType.objects.filter(name__in=[_("Workshop"), _("Academic"), _("Extracurricular")]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_subject_types, reverse_subject_types),
    ]
