# Generated by Django 5.1.6 on 2025-02-28 18:47
from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_event_types(apps, schema_editor):
    """
    Create default event types needed for the system.
    """
    EventType = apps.get_model("smiles", "EventType")

    # Create common event types
    event_types = [
        {
            "name": _("Enrollment"),
            "description": _("Enrollment period for subjects"),
            "metadata": {"requires_preview": True, "allows_modification": True},
        },
        {"name": _("Evaluation"), "description": _("Evaluation period for subjects"), "metadata": {"requires_grading": True}},
        {"name": _("Holiday"), "description": _("School holiday"), "metadata": {"cancels_classes": True}},
        {"name": _("Special Activity"), "description": _("Special school-wide activity"), "metadata": {"may_modify_schedule": True}},
        {"name": _("Parent Meeting"), "description": _("Parent-teacher meeting"), "metadata": {"attendance_required": True, "for_parents": True}},
    ]

    for et_data in event_types:
        EventType.objects.get_or_create(name=et_data["name"], defaults={"description": et_data["description"], "metadata": et_data["metadata"]})


def reverse_event_types(apps, schema_editor):
    """
    Remove created event types.
    """
    EventType = apps.get_model("smiles", "EventType")
    EventType.objects.filter(name__in=[_("Enrollment"), _("Evaluation"), _("Holiday"), _("Special Activity"), _("Parent Meeting")]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0002_create_subject_types"),
    ]

    operations = [
        migrations.RunPython(create_event_types, reverse_event_types),
    ]
