# Generated by Django 5.1.6 on 2025-02-28 18:48
from django.db import migrations


def migrate_cycles_to_groups(apps, schema_editor):
    """
    Convert Cycle models to Group models with group_type="Ciclo".
    """
    Cycle = apps.get_model("cayuman", "Cycle")
    Group = apps.get_model("smiles", "Group")

    # Create a mapping to store old cycle ID to new group ID for later use
    cycle_to_group_map = {}

    for cycle in Cycle.objects.all():
        group, _ = Group.objects.get_or_create(
            name=cycle.name,
            group_type="Ciclo",
            defaults={"description": cycle.description, "is_primary": True, "metadata": {"original_cycle_id": cycle.id}},  # Cycles are primary groups
        )

        # Store the mapping for later use in other migrations
        cycle_to_group_map[cycle.id] = group.id

    # Store the mapping in a separate model or file if needed for other migrations
    # This is a simple approach - in a real-world scenario, you might want to use a more robust method
    # to store this mapping between migrations

    # For demonstration, we'll print the mapping
    print(f"Cycle to Group mapping: {cycle_to_group_map}")


def reverse_cycles_to_groups(apps, schema_editor):
    """
    Remove groups created from cycles.
    """
    Group = apps.get_model("smiles", "Group")
    Group.objects.filter(group_type="Ciclo").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0003_create_event_types"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_cycles_to_groups, reverse_cycles_to_groups),
    ]
