# Generated by Django 5.1.6 on 2025-02-28 18:48
from django.db import migrations


def migrate_workshops_to_subjects(apps, schema_editor):
    """
    Convert workshops to Subjects with appropriate SubjectType.
    """
    Workshop = apps.get_model("cayuman", "Workshop")
    Subject = apps.get_model("smiles", "Subject")
    SubjectType = apps.get_model("smiles", "SubjectType")

    # Get the Workshop subject type (created in a previous migration)
    workshop_type = SubjectType.objects.get(name="Workshop")

    # Create a mapping to store old workshop ID to new subject ID for later use
    workshop_to_subject_map = {}

    for workshop in Workshop.objects.all():
        subject, created = Subject.objects.get_or_create(
            name=workshop.name,
            type=workshop_type,
            defaults={"description": workshop.description, "metadata": {"full_name": workshop.full_name, "original_workshop_id": workshop.id}},
        )

        # Store the mapping for later use in other migrations
        workshop_to_subject_map[workshop.id] = subject.id

    # For demonstration, we'll print the mapping
    print(f"Workshop to Subject mapping: {workshop_to_subject_map}")


def reverse_workshops_to_subjects(apps, schema_editor):
    """
    Remove subjects created from workshops.
    """
    Subject = apps.get_model("smiles", "Subject")
    SubjectType = apps.get_model("smiles", "SubjectType")

    workshop_type = SubjectType.objects.get(name="Workshop")
    Subject.objects.filter(type=workshop_type).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0004_migrate_cycles_to_groups"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_workshops_to_subjects, reverse_workshops_to_subjects),
    ]
