# Generated by Django 5.1.6 on 2025-02-28 18:48
from django.db import migrations
from django.utils.translation import gettext_lazy


def migrate_schedules_to_timeslots(apps, schema_editor):
    """
    Convert Schedule models to TimeSlot models.
    """
    Schedule = apps.get_model("cayuman", "Schedule")
    TimeSlot = apps.get_model("smiles", "TimeSlot")

    # Create a mapping to store old schedule ID to new timeslot ID for later use
    schedule_to_timeslot_map = {}

    # Define day choices mapping manually since we can't access Schedule.CHOICES in migrations
    day_choices = {
        "monday": gettext_lazy("Monday"),
        "tuesday": gettext_lazy("Tuesday"),
        "wednesday": gettext_lazy("Wednesday"),
        "thursday": gettext_lazy("Thursday"),
        "friday": gettext_lazy("Friday"),
    }

    for schedule in Schedule.objects.all():
        # Get the display name of the day
        day_display = day_choices.get(schedule.day, schedule.day)

        # Create a name for the time slot
        name = f"{day_display} {schedule.time_start.strftime('%H:%M')}-{schedule.time_end.strftime('%H:%M')}"

        timeslot, _ = TimeSlot.objects.get_or_create(
            day_of_week=schedule.day.lower(),
            time_start=schedule.time_start,
            time_end=schedule.time_end,
            defaults={"name": name, "metadata": {"original_schedule_id": schedule.id}},
        )

        # Store the mapping for later use in other migrations
        schedule_to_timeslot_map[schedule.id] = timeslot.id

    # For demonstration, we'll print the mapping
    print(f"Schedule to TimeSlot mapping: {schedule_to_timeslot_map}")


def reverse_schedules_to_timeslots(apps, schema_editor):
    """
    Remove timeslots created from schedules.
    """
    TimeSlot = apps.get_model("smiles", "TimeSlot")
    TimeSlot.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0005_migrate_workshops_to_subjects"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_schedules_to_timeslots, reverse_schedules_to_timeslots),
    ]
