# Generated by Django 5.1.6 on 2025-02-28 18:49
import datetime

from django.db import migrations
from django.utils import timezone


def migrate_periods_to_terms(apps, schema_editor):
    """
    Convert periods to Terms with appropriate metadata.
    """
    Period = apps.get_model("cayuman", "Period")
    Term = apps.get_model("smiles", "Term")
    Event = apps.get_model("smiles", "Event")
    EventType = apps.get_model("smiles", "EventType")
    Group = apps.get_model("smiles", "Group")

    # Get the Enrollment event type
    enrollment_type = EventType.objects.get(name="Enrollment")

    # Get all cycle groups
    cycle_groups = Group.objects.filter(group_type="Cycle")

    # Create a mapping to store old period ID to new term ID for later use
    period_to_term_map = {}

    for period in Period.objects.all():
        # Create the term
        term = Term.objects.create(
            name=period.name,
            term_type="Workshop Period",
            description=period.description,
            has_enrollment_period=True,
            date_start=period.date_start,
            date_end=period.date_end,
            metadata={"original_period_id": period.id},
        )

        # Store the mapping for later use in other migrations
        period_to_term_map[period.id] = term.id

        # Add enrollment period data to metadata
        enrollment_periods = []

        # Default enrollment end date if not specified
        enrollment_end = period.enrollment_end
        if not enrollment_end:
            enrollment_end = period.enrollment_start.date() + datetime.timedelta(days=5)

        enrollment_periods.append(
            {"name": "Regular", "start_date": period.enrollment_start.isoformat(), "end_date": enrollment_end.isoformat(), "group_types": ["Cycle"]}
        )

        term.metadata["enrollment_periods"] = enrollment_periods

        # Add preview date if available
        if period.preview_date:
            term.metadata["preview_date"] = period.preview_date.isoformat()

        term.save()

        # Create enrollment event for this term
        event_name = f"Enrollment {term.name}"

        # Use preview date or enrollment start date
        preview_date = period.preview_date if period.preview_date else period.enrollment_start

        # Make datetime objects timezone-aware
        # Handle preview_date
        if isinstance(preview_date, datetime.date) and not isinstance(preview_date, datetime.datetime):
            # Convert date to datetime
            preview_date = datetime.datetime.combine(preview_date, datetime.time.min)
            preview_date = timezone.make_aware(preview_date)
        elif isinstance(preview_date, datetime.datetime) and not timezone.is_aware(preview_date):
            # Make datetime timezone-aware
            preview_date = timezone.make_aware(preview_date)

        # Handle enrollment_start
        enrollment_start = period.enrollment_start
        if isinstance(enrollment_start, datetime.date) and not isinstance(enrollment_start, datetime.datetime):
            # Convert date to datetime
            enrollment_start = datetime.datetime.combine(enrollment_start, datetime.time.min)
            enrollment_start = timezone.make_aware(enrollment_start)
        elif isinstance(enrollment_start, datetime.datetime) and not timezone.is_aware(enrollment_start):
            # Make datetime timezone-aware
            enrollment_start = timezone.make_aware(enrollment_start)

        # Handle enrollment_end
        enrollment_end_datetime = enrollment_end
        if isinstance(enrollment_end_datetime, datetime.date) and not isinstance(enrollment_end_datetime, datetime.datetime):
            # Convert date to datetime with time at end of day
            enrollment_end_datetime = datetime.datetime.combine(enrollment_end_datetime, datetime.time.max)
            enrollment_end_datetime = timezone.make_aware(enrollment_end_datetime)
        elif isinstance(enrollment_end_datetime, datetime.datetime) and not timezone.is_aware(enrollment_end_datetime):
            # Make datetime timezone-aware
            enrollment_end_datetime = timezone.make_aware(enrollment_end_datetime)

        event = Event.objects.create(
            name=event_name,
            type=enrollment_type,
            term=term,
            preview_date=preview_date,
            date_start=enrollment_start,
            date_end=enrollment_end_datetime,
            is_active=True,
            metadata={
                "enrollment_period": "Regular",
                "group_types": ["Cycle"],
                "original_period_data": {
                    "id": period.id,
                    "enrollment_start": period.enrollment_start.isoformat(),
                    "enrollment_end": enrollment_end.isoformat() if enrollment_end else None,
                },
            },
        )

        # Associate with all cycle groups
        for group in cycle_groups:
            event.affects_groups.add(group)

    # For demonstration, we'll print the mapping
    print(f"Period to Term mapping: {period_to_term_map}")


def reverse_periods_to_terms(apps, schema_editor):
    """
    Remove terms created from periods.
    """
    Term = apps.get_model("smiles", "Term")
    Event = apps.get_model("smiles", "Event")
    EventType = apps.get_model("smiles", "EventType")

    # Get the Enrollment event type
    enrollment_type = EventType.objects.get(name="Enrollment")

    # Delete all enrollment events
    Event.objects.filter(type=enrollment_type).delete()

    # Delete all terms with term_type='Workshop Period'
    Term.objects.filter(term_type="Workshop Period").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0006_migrate_schedules_to_timeslots"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_periods_to_terms, reverse_periods_to_terms),
    ]
