# Generated by Django 5.1.6 on 2025-02-28 18:49
from django.db import migrations
from django.utils.translation import gettext_lazy as _


def migrate_workshop_periods_to_subject_offerings(apps, schema_editor):
    """
    Convert WorkshopPeriod models to SubjectOffering models.
    """
    WorkshopPeriod = apps.get_model("cayuman", "WorkshopPeriod")
    SubjectOffering = apps.get_model("smiles", "SubjectOffering")
    Subject = apps.get_model("smiles", "Subject")
    Term = apps.get_model("smiles", "Term")
    Group = apps.get_model("smiles", "Group")
    Event = apps.get_model("smiles", "Event")
    ActivityType = apps.get_model("smiles", "ActivityType")
    Activity = apps.get_model("smiles", "Activity")
    TimeSlot = apps.get_model("smiles", "TimeSlot")

    # Get or create the Class Session activity type
    class_session_type, __ = ActivityType.objects.get_or_create(
        name=_("Workshop Session"), defaults={"description": _("Regular workshop session"), "is_selectable": True, "requires_attendance": True}
    )

    # Create a mapping to store old workshop period ID to new subject offering ID for later use
    workshop_period_to_subject_offering_map = {}

    for wp in WorkshopPeriod.objects.all():
        # Get the corresponding subject, term, and enrollment event
        try:
            subject = Subject.objects.get(metadata__original_workshop_id=wp.workshop_id)
            term = Term.objects.get(metadata__original_period_id=wp.period_id)
            enrollment_event = Event.objects.filter(term=term, type__name=_("Enrollment")).first()

            # Create the subject offering
            offering = SubjectOffering.objects.create(
                subject=subject,
                term=term,
                teacher=wp.teacher,
                max_students=wp.max_students,
                enrollment_event=enrollment_event,
                metadata={"original_workshop_period_id": wp.id},
            )

            # Store the mapping for later use in other migrations
            workshop_period_to_subject_offering_map[wp.id] = offering.id

            # Associate with eligible groups (cycles)
            for cycle_id in wp.cycles.values_list("id", flat=True):
                group = Group.objects.filter(metadata__original_cycle_id=cycle_id).first()
                if group:
                    offering.eligible_groups.add(group)

            # Create activities for each schedule
            for schedule_id in wp.schedules.values_list("id", flat=True):
                timeslot = TimeSlot.objects.filter(metadata__original_schedule_id=schedule_id).first()
                if timeslot:
                    # Create an activity for this schedule
                    activity_name = f"{subject.name} - {timeslot.name}"
                    activity = Activity.objects.create(
                        name=activity_name,
                        type=class_session_type,
                        description=_(f"Class session for {subject.name}"),
                        subject_offering=offering,
                        metadata={"original_schedule_id": schedule_id},
                    )

                    # Associate with the same eligible groups as the offering
                    for group in offering.eligible_groups.all():
                        activity.applicable_groups.add(group)

        except (Subject.DoesNotExist, Term.DoesNotExist):
            print(f"Could not find corresponding subject or term for workshop period {wp.id}")
            continue

    # For demonstration, we'll print the mapping
    print(f"WorkshopPeriod to SubjectOffering mapping: {workshop_period_to_subject_offering_map}")


def reverse_workshop_periods_to_subject_offerings(apps, schema_editor):
    """
    Remove subject offerings created from workshop periods.
    """
    SubjectOffering = apps.get_model("smiles", "SubjectOffering")
    Activity = apps.get_model("smiles", "Activity")

    # Delete all activities related to subject offerings
    Activity.objects.filter(subject_offering__isnull=False).delete()

    # Delete all subject offerings
    SubjectOffering.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0007_migrate_periods_to_terms"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_workshop_periods_to_subject_offerings, reverse_workshop_periods_to_subject_offerings),
    ]
