# Generated by Django 5.1.6 on 2025-02-28 18:50
from django.db import migrations


def migrate_student_cycles_to_member_group_assignments(apps, schema_editor):
    """
    Convert StudentCycle models to MemberGroupAssignment models.
    """
    StudentCycle = apps.get_model("cayuman", "StudentCycle")
    MemberGroupAssignment = apps.get_model("smiles", "MemberGroupAssignment")
    Group = apps.get_model("smiles", "Group")
    SubjectOffering = apps.get_model("smiles", "SubjectOffering")

    # Create a mapping to store old student cycle ID to new member group assignment ID for later use
    student_cycle_to_member_group_assignment_map = {}

    for sc in StudentCycle.objects.all():
        # Get the corresponding group
        try:
            group = Group.objects.get(metadata__original_cycle_id=sc.cycle_id)

            # Create the member group assignment
            assignment = MemberGroupAssignment.objects.create(
                member=sc.student, group=group, date_assigned=sc.date_joined, is_active=True, metadata={"original_student_cycle_id": sc.id}
            )

            # Store the mapping for later use in other migrations
            student_cycle_to_member_group_assignment_map[sc.id] = assignment.id

            # Associate with subject offerings (workshop periods)
            for wp_id in sc.workshop_periods.values_list("id", flat=True):
                offering = SubjectOffering.objects.filter(metadata__original_workshop_period_id=wp_id).first()
                if offering:
                    assignment.subject_offerings.add(offering)

        except Group.DoesNotExist:
            print(f"Could not find corresponding group for student cycle {sc.id}")
            continue

    # For demonstration, we'll print the mapping
    print(f"StudentCycle to MemberGroupAssignment mapping: {student_cycle_to_member_group_assignment_map}")


def reverse_student_cycles_to_member_group_assignments(apps, schema_editor):
    """
    Remove member group assignments created from student cycles.
    """
    MemberGroupAssignment = apps.get_model("smiles", "MemberGroupAssignment")
    MemberGroupAssignment.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0008_migrate_workshop_periods_to_subject_offerings"),
        ("cayuman", "0001_initial"),  # Make sure cayuman models are available
    ]

    operations = [
        migrations.RunPython(migrate_student_cycles_to_member_group_assignments, reverse_student_cycles_to_member_group_assignments),
    ]
