# Generated by Django 5.1.6 on 2025-02-28 18:50
from django.db import migrations
from django.utils.translation import gettext_lazy as _


def migrate_schedule_relationships(apps, schema_editor):
    """
    Create schedule templates and assignments based on existing data.
    """
    Term = apps.get_model("smiles", "Term")
    Group = apps.get_model("smiles", "Group")
    TimeSlot = apps.get_model("smiles", "TimeSlot")
    Activity = apps.get_model("smiles", "Activity")
    ScheduleTemplate = apps.get_model("smiles", "ScheduleTemplate")
    ScheduleAssignment = apps.get_model("smiles", "ScheduleAssignment")
    MemberGroupAssignment = apps.get_model("smiles", "MemberGroupAssignment")
    MemberSchedule = apps.get_model("smiles", "MemberSchedule")

    # Create schedule templates for each term and group combination
    for term in Term.objects.all():
        for group in Group.objects.filter(group_type=_("Cycle")):
            # Create a schedule template for this term and group
            template_name = _(f"{group.name} Schedule - {term.name}")
            template = ScheduleTemplate.objects.create(
                name=template_name,
                description=_(f"Schedule template for {group.name} during {term.name}"),
                metadata={"term_id": term.id, "group_id": group.id},
            )

            # Associate with the group and term
            template.applicable_groups.add(group)
            template.applicable_terms.add(term)

            # Find all activities that apply to this group and term
            activities = Activity.objects.filter(applicable_groups=group, subject_offering__term=term)

            # Create schedule assignments for each activity
            for activity in activities:
                # Find the time slot for this activity
                if "original_schedule_id" in activity.metadata:
                    timeslot = TimeSlot.objects.filter(metadata__original_schedule_id=activity.metadata["original_schedule_id"]).first()

                    if timeslot:
                        # Check if this assignment already exists to avoid duplicates
                        existing_assignment = ScheduleAssignment.objects.filter(template=template, time_slot=timeslot).exists()

                        if not existing_assignment:
                            # Create a schedule assignment
                            ScheduleAssignment.objects.create(template=template, time_slot=timeslot, activity=activity)

    # Create member schedules for each member group assignment
    for assignment in MemberGroupAssignment.objects.all():
        # Find all terms where this member has subject offerings
        term_ids = assignment.subject_offerings.values_list("term_id", flat=True).distinct()

        for term_id in term_ids:
            term = Term.objects.get(id=term_id)

            # Find the template for this group and term
            template = ScheduleTemplate.objects.filter(applicable_groups=assignment.group, applicable_terms=term).first()

            if template:
                # Check if this member schedule already exists
                existing_schedule = MemberSchedule.objects.filter(member=assignment.member, term=term, template=template).exists()

                if not existing_schedule:
                    # Create a member schedule
                    MemberSchedule.objects.create(
                        member=assignment.member,
                        term=term,
                        template=template,
                        is_custom=False,
                        metadata={"member_group_assignment_id": assignment.id},
                    )


def reverse_schedule_relationships(apps, schema_editor):
    """
    Remove schedule templates and assignments.
    """
    ScheduleTemplate = apps.get_model("smiles", "ScheduleTemplate")
    MemberSchedule = apps.get_model("smiles", "MemberSchedule")

    # Delete all member schedules
    MemberSchedule.objects.all().delete()

    # Delete all schedule templates (will cascade to schedule assignments)
    ScheduleTemplate.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0009_migrate_student_cycles_to_member_group_assignments"),
    ]

    operations = [
        migrations.RunPython(migrate_schedule_relationships, reverse_schedule_relationships),
    ]
