# Generated by Django 5.1.6 on 2025-02-28 18:51
from django.db import migrations


def finalize_migration(apps, schema_editor):
    """
    Perform final checks and cleanup after migration.
    """
    # Get all the models
    Subject = apps.get_model("smiles", "Subject")
    SubjectOffering = apps.get_model("smiles", "SubjectOffering")
    Term = apps.get_model("smiles", "Term")
    Group = apps.get_model("smiles", "Group")
    MemberGroupAssignment = apps.get_model("smiles", "MemberGroupAssignment")
    TimeSlot = apps.get_model("smiles", "TimeSlot")
    Activity = apps.get_model("smiles", "Activity")
    ScheduleTemplate = apps.get_model("smiles", "ScheduleTemplate")
    ScheduleAssignment = apps.get_model("smiles", "ScheduleAssignment")
    MemberSchedule = apps.get_model("smiles", "MemberSchedule")
    Event = apps.get_model("smiles", "Event")

    # Print summary of migrated data
    print("Migration Summary:")
    print(f"- Subjects: {Subject.objects.count()}")
    print(f"- Subject Offerings: {SubjectOffering.objects.count()}")
    print(f"- Terms: {Term.objects.count()}")
    print(f"- Groups: {Group.objects.count()}")
    print(f"- Member Group Assignments: {MemberGroupAssignment.objects.count()}")
    print(f"- Time Slots: {TimeSlot.objects.count()}")
    print(f"- Activities: {Activity.objects.count()}")
    print(f"- Schedule Templates: {ScheduleTemplate.objects.count()}")
    print(f"- Schedule Assignments: {ScheduleAssignment.objects.count()}")
    print(f"- Member Schedules: {MemberSchedule.objects.count()}")
    print(f"- Events: {Event.objects.count()}")

    # Check for any missing relationships
    missing_relationships = []

    # Check if any subject offerings don't have an enrollment event
    offerings_without_event = SubjectOffering.objects.filter(enrollment_event__isnull=True)
    if offerings_without_event.exists():
        missing_relationships.append(f"{offerings_without_event.count()} subject offerings don't have an enrollment event")

    # Check if any member group assignments don't have subject offerings
    assignments_without_offerings = MemberGroupAssignment.objects.filter(subject_offerings__isnull=True)
    if assignments_without_offerings.exists():
        missing_relationships.append(f"{assignments_without_offerings.count()} member group assignments don't have subject offerings")

    # Check if any activities don't have applicable groups
    activities_without_groups = Activity.objects.filter(applicable_groups__isnull=True)
    if activities_without_groups.exists():
        missing_relationships.append(f"{activities_without_groups.count()} activities don't have applicable groups")

    # Print missing relationships
    if missing_relationships:
        print("\nWarning: Missing Relationships:")
        for msg in missing_relationships:
            print(f"- {msg}")
    else:
        print("\nAll relationships are properly set up.")

    print("\nMigration completed successfully!")


def reverse_finalize_migration(apps, schema_editor):
    """
    No-op reverse migration.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("smiles", "0010_migrate_schedule_relationships"),
    ]

    operations = [
        migrations.RunPython(finalize_migration, reverse_finalize_migration),
    ]
