# Generated by Django 5.1.6 on 2025-03-01 02:51
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    dependencies = [
        ("cayuman", "0006_alter_period_enrollment_start"),
        ("smiles", "0011_finalize_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": _("Attendance record"), "verbose_name_plural": _("Attendance records")},
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="activity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="smiles.activity", verbose_name=_("Activity")
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attended",
            field=models.BooleanField(default=True, verbose_name=_("Attended")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name=_("Date")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="early_dismissal_time",
            field=models.TimeField(blank=True, null=True, verbose_name=_("Early dismissal time")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="late_arrival_time",
            field=models.TimeField(blank=True, null=True, verbose_name=_("Late arrival time")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="cayuman.member", verbose_name=_("Member")
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, help_text=_("Attendance-specific attributes"), verbose_name=_("Metadata")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True, verbose_name=_("Notes")),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendance",
                to="cayuman.member",
                verbose_name=_("Recorded by"),
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="smiles.timeslot", verbose_name=_("Time slot")
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="membergroupassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="membergroupassignment",
            name="date_assigned",
            field=models.DateField(auto_now_add=True, help_text=_("When this assignment happened"), verbose_name=_("Date assigned")),
        ),
        migrations.AlterField(
            model_name="membergroupassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="memberschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="memberschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="memberscheduleoverride",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="memberscheduleoverride",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="scheduleassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="scheduleassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="specialday",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="specialday",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="subjectoffering",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="subjectoffering",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="subjecttype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="subjecttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="term",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="term",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("Created at")),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name=_("Updated at")),
        ),
    ]
